name: MLflow CI - Prediksi Stunting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow pandas scikit-learn xgboost

    - name: Create mlruns folder
      run: mkdir -p MLProject/mlruns

    - name: Run Training with MLflow Project
      working-directory: MLProject
      run: mlflow run . --env-manager=local


    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker Image with MLflow
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:./mlruns
      run: |
        echo "Isi mlruns:"
        find mlruns -maxdepth 4

        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | head -n 1)

        echo "Model path ditemukan:"
        echo "$MODEL_PATH"

        mlflow models build-docker \
          --model-uri "$MODEL_PATH" \
          --name stunting-xgboost

    - name: Tag & Push Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        DOCKER_USER_CLEAN=$(printf "%s" "$DOCKER_USER")
        IMAGE_NAME="${DOCKER_USER_CLEAN}/stunting-xgboost:latest"

        echo "Tagging image as $IMAGE_NAME"
        docker tag stunting-xgboost "$IMAGE_NAME"
        docker push "$IMAGE_NAME"

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns
