name: MLflow CI - Stunting XGBoost

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install MLflow
      run: |
        python -m pip install --upgrade pip
        pip install mlflow xgboost scikit-learn pandas numpy matplotlib seaborn


    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local


    - name: Commit and push MLflow artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add MLProject/mlruns
        git commit -m "Update MLflow artifacts (CI training)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest MLflow model artifact path
      id: get_model_path
      run: |
        MODEL_PATH=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort -r | head -n 1)
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
        echo "Latest model path: $MODEL_PATH"

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    
    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m $MODEL_PATH -n hafidsopie/stunting-xgboost


    - name: Push Docker image to Docker Hub
      run: |
        docker push hafidsopie/stunting-xgboost
