name: MLflow CI Docker

on: [push, workflow_dispatch]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mlflow xgboost scikit-learn pandas
          
      - name: Run MLflow Project
        run: |
          mlflow run . \
            --env-manager=local \
            -P data_path=stunting_wasting_preprocessed.csv

      - name: Get latest run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-name "Stunting Classification - XGBoost" --max-results 1 | tail -n 1 | awk '{print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "âœ… RUN_ID=$RUN_ID"

      - name: Build Docker image
        run: |
          mlflow models build-docker -m runs:/$RUN_ID/model -n hafidsopi/stunting-xgboost
