name: MLflow CI Docker

on:
  push:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow xgboost scikit-learn pandas

      - name: Run MLflow Project
        run: |
          mlflow run . \
            --env-manager=local \
            -P data_path=stunting_wasting_preprocessed.csv

      - name: Find latest MLflow model
        run: |
          MODEL_PATH=$(find mlruns -type d -name model | head -n 1)
          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
          echo "Model path: $MODEL_PATH"

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          mlflow models build-docker \
            -m $MODEL_PATH \
            -n hafidsopie/stunting-xgboost

      - name: Push Docker image
        run: |
          docker push hafidsopie/stunting-xgboost
